[package]
name = "hey"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chat-gpt-lib-rs = "0.2.1"
colored = "2.0.4"
dotenv = "0.15.0"
spinners = "4.1.0"
tokio = "1.33.0"
