installUbuntu git
installUbuntu zsh
installUbuntu tmux
installUbuntu curl
installUbuntu wget
installUbuntu build-essential
installUbuntu libbz2-dev
installUbuntu libdb-dev
installUbuntu libreadline-dev
installUbuntu libffi-dev
installUbuntu libgdbm-dev
installUbuntu liblzma-dev
installUbuntu libncursesw5-dev
installUbuntu libsqlite3-dev
installUbuntu libssl-dev
installUbuntu zlib1g-dev
installUbuntu uuid-dev
installUbuntu tk-dev
installUbuntu llvm
installUbuntu clang
installUbuntu cmake
installUbuntu protobuf-compiler
installUbuntu ca-certificates

installMac reattach-to-user-namespace
installMac tmux
installMac cmake
installMac gpg
installMac pipx
