source ~/.dotfiles/zsh/lib.sh

# Import basic settings before loading others
source ~/.dotfiles/zsh/preload.sh

source ~/.dotfiles/zsh/plugins/zinit.sh

# Import standard settings
loadsh ~/.dotfiles/zsh/zsh-configs.sh
loadsh ~/.dotfiles/zsh/history.sh
loadsh ~/.dotfiles/zsh/export-path.sh
loadsh ~/.dotfiles/zsh/symbolic-link.sh
loadsh ~/.dotfiles/zsh/dotfiles-private.sh

# Import plugins settings
loadsh ~/.dotfiles/zsh/plugins/brew.sh
loadsh ~/.dotfiles/zsh/plugins/pkg.sh
loadsh ~/.dotfiles/zsh/plugins/tmux.sh
loadsh ~/.dotfiles/zsh/plugins/fzf.sh
loadsh ~/.dotfiles/zsh/plugins/gomi.sh
loadsh ~/.dotfiles/zsh/plugins/protobuf.sh
loadsh ~/.dotfiles/zsh/plugins/gh.sh
loadsh ~/.dotfiles/zsh/plugins/cargo.sh
loadsh ~/.dotfiles/zsh/plugins/anyenv.sh
loadsh ~/.dotfiles/zsh/plugins/go.sh
loadsh ~/.dotfiles/zsh/plugins/poetry.sh
loadsh ~/.dotfiles/zsh/plugins/deno.sh
loadsh ~/.dotfiles/zsh/plugins/nvim.sh
loadsh ~/.dotfiles/zsh/plugins/kubectl.sh
loadsh ~/.dotfiles/zsh/plugins/krew.sh
loadsh ~/.dotfiles/zsh/plugins/zoxide.sh

# Completion settings
loadsh ~/.dotfiles/zsh/completion.sh

# Import local settings
loadsh ~/.dotfiles/zsh/localconfig.sh
